// Ədədlə (vahid) alınan məhsulların siyahısı
window.PIECE_PRODUCTS = [
  "Çörək alış",
  "Qarpız alış",
  "Yumurta alış",
  "Bulyon alış",
  "Lavaş alış",
  "Toyuq alış",
  "Paxlava alış",
  "Plitka şokolad alış",
  "Şəkərbura alış",
  "Efes(0,33) alış",
  "Efes(0,5) alış",
  "Lowenbrau(0,5) alış",
  "Borjomi alış",
  "Fanta(0.200) alış",
  "Fanta(0.5) alış",
  "Kola(0.200) alış",
  "Kola(0.5) alış",
  "Nabeğlavi alış",
  "Nataxtari alış",
  "Red Bull(0,250) alış",
  "Sprite(0.5) alış",
  "XL(0,250) alış",
  "Cappy(0,5) alış",
  "Kompot alış",
  "Sno limon alış",
  "Sno plasmas alış",
  "Sno şüşə alış",
  "Moet Chandon alış",
  "Cheesecake alış",
  "Tiramisu alış",
  "Ekler alış",
  "Tartaletka alış",
  "Blin tortu alış",
  "Kola(0.33) alış",
  "Fanta(0.33) alış",
  "Yemiş alış",
  "Staropramen(0.5) alış",
  "T.V - Şampan alış",
  "Badambura alış",
  "Heineken(0.33) alış",
  "Bildirçin alış",
  "Toyuq boğazı alış",
  "Hisəverilmiş farel alış",
  "Hisəverilmiş dorado alış",
  "İçalat alış",
  "Sno(0,33) - şüşə alış",
  "Medok alış",
  "Farel alış",
  "Sibas alış"
];

window.OTHER_PRODUCTS = [
  "Acı bibər alış",
  "Aerozol alış",
  "Ağ kələm turşusu alış",
  "Ağ pendir alış",
  "Ağac alış",
  "Albalı turşusu alış",
  "Alça alış",
  "Alça qurusu alış",
  "Alça sousu alış",
  "Alça turşusu alış",
  "Alışqan alış",
  "Alma turşusu alış",
  "Ananas alış",
  "Antifriz alış",
  "Aparat kofesi alış",
  "Armud alış",
  "Aromatizator alış",
  "Asetrin alış",
  "Askaneli-3 alış",
  "Askaneli-5 alış",
  "Askaneli-6 alış",
  "Askaneli-8 alış",
  "Astar şlank alış",
  "Badam alış",
  "Badımcan alış",
  "Badımcan turşusu alış",
  "Bakal alış",
  "Bal alış",
  "Balaca rolik alış",
  "Balış alış",
  "Balış üzü alış",
  "Ballantines alış",
  "Banan alış",
  "Baner alış",
  "Batareya alış",
  "Beluga alış",
  "Benzin alış",
  "Bibər turşusu alış",
  "Bıçaq alış",
  "Bitki yağı alış",
  "Bloknot alış",
  "Borjomi alış",
  "Böyük rolik alış",
  "Budweiser-draft alış",
  "Buğda alış",
  "Bülöv bıçaq alış",
  "Bulqur alış",
  "Bulud qab alış",
  "Bulyon alış",
  "Buz alış",
  "Camsil alış",
  "Can əti alış",
  "Cappy(0,5) alış",
  "Çay alış",
  "Çay balığı alış",
  "Çay qaşığı alış",
  "Cəftə alış",
  "Çəkələk alış",
  "Celsi alış",
  "Çəngəl alış",
  "Cənnətalması turşusu alış",
  "Chacha-Askaneli-Gold alış",
  "Cherry pomidor alış",
  "Chivas Regal-12 alış",
  "Chivas Regal-18 alış",
  "Çilçıraq alış",
  "CO qazı alış",
  "Çolpa alış",
  "Concoli turşusu alış",
  "Çörək alış",
  "Courvoisier VS alış",
  "Çuğundur alış",
  "Buzov alış",
  "Dana beli alış",
  "Dana qabırğası alış",
  "De lux - Nemiroff alış",
  "Dəfnə yarpağı alış",
  "Dəmir list alış",
  "Dəsmal alış",
  "Dezobaryer alış",
  "Dibçək alış",
  "Dırnaq alış",
  "Diş çöpü alış",
  "Dispenser-Z alış",
  "Doğrama taxtası alış",
  "Domestos alış",
  "Dondurma alış",
  "Drel alış",
  "Droj alış",
  "Düyü alış",
  "Duz alış",
  "Ədyal alış",
  "Efes(0,33) alış",
  "Efes(0,5) alış",
  "E-keeper çeki alış",
  "Əlcək alış",
  "Elektrik çaydanı alış",
  "Elektrik çəngəli alış",
  "Elektrot alış",
  "Emusya alış",
  "Erdinger-draft alış",
  "Ərik qurusu alış",
  "Erkək quyruğu alış",
  "Estrella(0,33) alış",
  "Estrella(0,5) alış",
  "Ət maşını bıçağı alış",
  "Əyri alış",
  "Əzgil turşusu alış",
  "Fanta(0.200) alış",
  "Fanta(0.5) alış",
  "Farel alış",
  "Farel-böyük alış",
  "Fen alış",
  "Feyri alış",
  "File alış",
  "Fındıq alış",
  "Finlandiya alış",
  "Finski alış",
  "Fırça alış",
  "Folqa alış",
  "Fri alış",
  "Fri aparatı alış",
  "Fum alış",
  "Gavalı turşusu alış",
  "Gips alış",
  "Göbələk alış",
  "Göbələk konservi alış",
  "Göyəm turşusu alış",
  "Göyərti alış",
  "Grey Goose alış",
  "Gül alış",
  "Günəbaxan yağı alış",
  "Gürcü xinkali alış",
  "Hennesy-VS alış",
  "Meyvə arağı alış",
  "Heyva turşusu alış",
  "Hinduşka alış",
  "Hisəverilmiş sulguni alış",
  "İçalat alış",
  "İmeruli xaçapuri alış",
  "İndikator alış",
  "İşıqlı ağac alış",
  "İspanaq alış",
  "İzolent alış",
  "Jack Daniels alış",
  "Jagermeister alış",
  "Jameson alış",
  "Jim Beam alış",
  "Johnnie Walker-black alış",
  "Johnnie Walker-red alış",
  "Kabab taxtası alış",
  "Kabel alış",
  "Kabel qovşağı alış",
  "Kafel alış",
  "Kah Blanko alış",
  "Kahı alış",
  "Kalakuri ağ çəllək çaxırı alış",
  "Kalonka alış",
  "Kambala alış",
  "Kartof alış",
  "Kassa çeki alış",
  "Keçirici alış",
  "Kəklikotu alış",
  "Kələm alış",
  "Kəllə-paça alış",
  "Kəndir alış",
  "Kərə yağı alış",
  "Ketçup alış",
  "Kilbeggan alış",
  "Kişmiş alış",
  "Kofe alış",
  "Kök alış",
  "Kök ədavası alış",
  "Kola(0.200) alış",
  "Kola(0.5) alış",
  "Kolbasa alış",
  "Kompot alış",
  "Kömür alış",
  "Konfet alış",
  "Konteyner alış",
  "Krant alış",
  "Külləmə kartof alış",
  "Künc alış",
  "Lak alış",
  "Lampuçka alış",
  "Laqonda daşı alış",
  "Lavaş alış",
  "LED işıq alış",
  "Ləyən alış",
  "Leyko plaster alış",
  "Limon alış",
  "Limon çəngəli alış",
  "Limon duzu alış",
  "Limon suyu alış",
  "Lobya alış",
  "Lowenbrau(0,5) alış",
  "Lukum alış",
  "Maçalka alış",
  "Makaron alış",
  "Mal dili alış",
  "Mal əti alış",
  "Mal pendiri alış",
  "Mandarin alış",
  "Marla alış",
  "Maska alış",
  "Mata alış",
  "Matras alış",
  "Maye sabun alış",
  "Mayonez alış",
  "Medoff alış",
  "Meqrel ajikası alış",
  "Mərcimək alış",
  "Mətbəx alışqanı alış",
  "Mətbəx papağı alış",
  "Meyvə alış",
  "Meyvə qurusu alış",
  "Mikrodalğalı soba alış",
  "Milad gülü alış",
  "Mismar alış",
  "Mixək alış",
  "Moet Chandon alış",
  "Motal pendiri alış",
  "Mouse alış",
  "Mürəbbə alış",
  "Müşdük alış",
  "Nabeğlavi alış",
  "Naqqaş alış",
  "Nar sousu alış",
  "Narşərab alış",
  "Nataxtari alış",
  "Natural sok alış",
  "Nəlbəki alış",
  "Nəm salfetka alış",
  "Nemiroff alış",
  "Noxud alış",
  "Önlük alış",
  "Oraquli alış",
  "Ördək alış",
  "Paket alış",
  "Paltaryuyan alış",
  "Paraşok alış",
  "Parça alış",
  "Parmezan pendiri alış",
  "Paxlava alış",
  "Pesok alış",
  "Petlə alış",
  "Pip yarpağı alış",
  "Plasmas bolt alış",
  "Plasmas qab alış",
  "Plasmas turba alış",
  "Plasmas ütüsü alış",
  "Plitka şokolad alış",
  "Pomidor alış",
  "Pomidor turşusu alış",
  "Profil alış",
  "Pul bibər alış",
  "Qab maçalkası alış",
  "Qab şampunu alış",
  "Qab setkası alış",
  "Qara istiot alış",
  "Qara zeytun alış",
  "Qarabaşaq alış",
  "Qarğıdalı konservi alış",
  "Qarğıdalı yağı alış",
  "Qarpız alış",
  "Qaşıq alış",
  "Qatıq alış",
  "Qauda pendiri alış",
  "Qayçı alış",
  "Qaymaq alış",
  "Qaymə alış",
  "Qaz qızdırıcısı alış",
  "Qələm alış",
  "Qəlyan kömürü alış",
  "Qəlyan tütünü alış",
  "Qənd alış",
  "Qıfıl alış",
  "Qırmızı alma alış",
  "Qırmızı bolqar alış",
  "Qırmızı çəllək çaxırı alış",
  "Qırmızı istiot alış",
  "Qırmızı pomidor tutması alış",
  "Qırmızı soğan alış",
  "Qiymət kağızı alış",
  "Qoyun pendiri alış",
  "Qoz alış",
  "Qreyfrut alış",
  "Quru lobya alış",
  "Quru nanə alış",
  "Qurud alış",
  "Quzu alış",
  "Razetka alış",
  "Red Bull(0,250) alış",
  "Rəng alış",
  "Rozmarin alış",
  "Rumka alış",
  "Russkaya alış",
  "Russki Standart - Platinum alış",
  "Russki Standart alış",
  "Şabalıd alış",
  "Şaftalı arağı alış",
  "Saima - Hot ice alış",
  "Salfetka alış",
  "Şam ağacı alış",
  "Santiago de Cuba-black alış",
  "Santiago de Cuba-white alış",
  "Sarafan alış",
  "Sarajişvili VS alış",
  "Sarajişvili VSOP alış",
  "Sarı bolqar alış",
  "Sarıkök alış",
  "Sarımsaq alış",
  "Sarımsaq turşusu alış",
  "Sauza Gold alış",
  "Sauza Silver alış",
  "Şaxta baba alış",
  "Şəkər pudrası alış",
  "Şəkərbura alış",
  "Səməni alış",
  "Sement mikseri alış",
  "Setka alış",
  "Sezar sousu alış",
  "Sifon şlankı alış",
  "Silikon alış",
  "Sini alış",
  "Siqaret alış",
  "Sirkə alış",
  "Şirniyyat alış",
  "Şiş alış",
  "Skoç alış",
  "Sumbata alış",
  "Skumbriya alış",
  "Şlank alış",
  "Smetan alış",
  "Sno limon alış",
  "Sno plasmas alış",
  "Sno şüşə alış",
  "Soba borusu alış",
  "Sobieski alış",
  "Soda alış",
  "Soğan alış",
  "Şor alış",
  "Sosiska alış",
  "Sous şüşəsi alış",
  "Soya sous alış",
  "Soyuducu alış",
  "Spagetti alış",
  "Şpaklovka alış",
  "Şpatel alış",
  "Spirt alış",
  "Sprite(0.5) alış",
  "Şprot alış",
  "Şrup alış",
  "Stəkan alış",
  "Stoliçnaya alış",
  "Ştoper alış",
  "Streç alış",
  "Su alış",
  "Süd alış",
  "Süfrə alış",
  "Süfrə bıçağı alış",
  "Suletka alış",
  "Sulguni alış",
  "Sulguni fətiri alış",
  "Şumanit alış",
  "Sumax alış",
  "Sümüklü mal əti alış",
  "Sunel alış",
  "Sunel oregano alış",
  "Sünii gül alış",
  "Sünii pambıq alış",
  "Süpürgə alış",
  "Suxarı alış",
  "Sverlo alış",
  "Syomka alış",
  "T.V - Kindzmarauli alış",
  "T.V - Saperavi alış",
  "T.V - Tsinandali alış",
  "T.V - Tvişi alış",
  "T.V-Chacha-gold alış",
  "T.V-Chacha-white alış",
  "Tarelka-A alış",
  "Tarelka-B alış",
  "Tava alış",
  "Taxta alış",
  "Taxta sverlo alış",
  "Termometr alış",
  "Tkemali alış",
  "Tkemali turşusu alış",
  "Tomat alış",
  "Torado alış",
  "Torpaq alış",
  "Toyuq alış",
  "Toyuq budu alış",
  "Traynik alış",
  "Traynik plasmas alış",
  "Tualet dərmanı alış",
  "Tualet kağızı alış",
  "Türk bibəri turşusu alış",
  "Türk kofesi alış",
  "Türk paxlavası alış",
  "Turp alış",
  "Un alış",
  "Unitaz yapışqanı alış",
  "USB-kabel alış",
  "Üzüm yarpağı alış",
  "Xamut alış",
  "Xardal alış",
  "Xırda lobya alış",
  "Xırda soğan alış",
  "Xiyar alış",
  "Xiyar turşusu alış",
  "XL(0,250) alış",
  "Xlor alış",
  "Xortum alış",
  "Xurma alış",
  "Yaşıl bolqar alış",
  "Yaşıl noxud alış",
  "Yaşıl zeytun alış",
  "Yeni il Maralı alış",
  "Yeni il oyuncağı alış",
  "Yeni il palması alış",
  "Yeni il tacı alış",
  "Yeni il topu alış",
  "Yumru düyü alış",
  "Yumru istiot alış",
  "Yumurta alış",
  "Yunan qozu alış",
  "Zəfəran alış",
  "Zeytun yağı alış",
  "Zibil paketi alış",
  "Zınqırov alış",
  "Zoğal alış",
  "Zoğal turşusu alış",
  "Zubrowka alış",
  "Zubrowka-Bizon gras alış",
  "Zubrowka-Gold alış",
  "Qida rəngi alış",
  "Vedrə alış",
  "Darçın alış",
  "Şar alış",
  "Kalkulyator alış",
  "Mətbəx tərəzisi alış",
  "Sous qabı alış",
  "Plasmas borucuq alış",
  "Çipsi alış",
  "Araxis alış",
  "Cheesecake alış",
  "Tiramisu alış",
  "Ekler alış",
  "Tartaletka alış",
  "Blin tortu alış",
  "Toyuq çubuqları alış",
  "Qəlyan şlankı alış",
  "Qabartma tozu alış",
  "Xramuli alış",
  "Satali balığı alış",
  "Mal qarını alış",
  "Boşqab alış",
  "Duzqabı alış",
  "İstiotqabı alış",
  "Çaxır stəkanı alış",
  "Soyuq kofe stəkanı alış",
  "Yoqurt alış",
  "Kvadrat profil alış",
  "Kola(0.33) alış",
  "Fanta(0.33) alış",
  "Darkside tütünü alış",
  "Sterlyad alış",
  "Yemiş alış",
  "Blinçik alış",
  "Staropramen(0.5) alış",
  "Pizza sobası alış",
  "Beefeater alış",
  "Martini alış",
  "Bacardi alış",
  "Serebro alış",
  "Pizza çömçəsi alış",
  "Pizza bişirmə setkası alış",
  "Nişasta alış",
  "Dairəvi şüşə list alış",
  "Dörd künc şüşə list alış",
  "Konvert alış",
  "Stepler alış",
  "Şam alış",
  "Balaca fişəng alış",
  "Süzmə alış",
  "Racia alış",
  "Qulaqlıq alış",
  "T.V - Şampan alış",
  "Sprey rəng alış",
  "Malyar skoçu alış",
  "Plasmas kəsici alış",
  "Aşsüzən alış",
  "Zibil qabı alış",
  "Plasmas duvax alış",
  "Konteyner qapağı alış",
  "Ventilyator alış",
  "Toster alış",
  "Fənər alış",
  "Yanğınsöndürən alış",
  "Yanğınsöndürən asılqanı alış",
  "Sous butulkası alış",
  "Kuller alış",
  "Razetka çərçivəsi alış",
  "Qapı alış",
  "Qum alış",
  "Plasmas dubil alış",
  "Kley alış",
  "Zəncəfil unu alış",
  "Vizitka alış",
  "Aspirator alış",
  "Döşəmə silən ağac alış",
  "Aseton alış",
  "Divar kağızı alış",
  "Proyektor alış",
  "Proyektor pərdəsi alış",
  "Yumşaq stul alış",
  "Çaxır tərəcəsi alış",
  "İkitərəfli skoç alış",
  "Dəmir sini ayaqlı alış",
  "Xəkandaz alış",
  "Qoruyucu klapan alış",
  "Plasmas krant alış",
  "Tərəvəz tərəcəsi alış",
  "Gül qayçısı alış",
  "QR tutacağı alış",
  "Yerləndirici qurğu alış",
  "Avtomat açar alış",
  "Polimer boru alış",
  "Sabun alış",
  "Wi-Fi router alış",
  "Flayer alış",
  "Lampa patronu alış",
  "Kabel tutucu alış",
  "Naqqa balığı alış",
  "Bildirçin alış",
  "Termal printer alış",
  "Kassa alış",
  "Şəbəkə sviçi alış",
  "RJ45 alış",
  "Qaynaq tüstüsü soran alış",
  "Sərt disk alış",
  "Qida bloku alış",
  "Topinq alış",
  "T.V - Alazani Valley alış",
  "Jilet alış",
  "Köynək alış",
  "Elektrik qızdırıcısı alış",
  "Enerji \"Buğa\" alış",
  "Neylon sıxıcı alış",
  "Mebel taxtası alış",
  "T.V - Axaşeni alış",
  "Absolut alış",
  "Sifon alış",
  "Unitaz oturacağı alış",
  "Danzka alış",
  "Sarajişvili-3 alış",
  "Kabel kanalı alış",
  "Qaz alış",
  "Siqa balığı alış",
  "Sazan balığı alış",
  "Dəftər alış",
  "Mişar ağzı alış",
  "Vintaçan alış",
  "Kəsici disk alış",
  "Olmeca Blanko alış",
  "Badambura alış",
  "Heineken(0.33) alış",
  "T.V - Mukuzani alış",
  "T.V - Pirosmani ağ alış",
  "Kvareli - Kindzmarauli Marani alış",
  "Kisi - Kindzmarauli Marani alış",
  "T.V - Pirosmani qırmızı alış",
  "T.V - Yaşıl Kisi alış",
  "Şrup başı alış",
  "Yağlı kağız alış",
  "Balta alış",
  "Dərman alış",
  "Çaynik alış",
  "Zirinc alış",
  "Suvax malası alış",
  "Mala alış",
  "Dəftərxana bıçağı alış",
  "Dəftərxana bıçağı ağzı alış",
  "Silikon aparatı alış",
  "Rəngləmə teleskopu alış",
  "Ariston alış",
  "Debriyaz rezini alış",
  "Toyuq boğazı alış",
  "Pətənək alış",
  "Hisəverilmiş farel alış",
  "Hisəverilmiş dorado alış",
  "Saçaq pendir alış",
  "Sabun qabı alış",
  "Samovar alış",
  "Paduga alış",
  "Asma tavan alış",
  "Üçlü divan alış",
  "Masa alış",
  "Sno(0,33) - şüşə alış",
  "Medok alış",
  "Dondurma qabı alış",
  "Qəlyan çaşkası alış",
  "Parking dirəyi alış",
  "Yol konusu alış",
  "Televizor alış",
  "Ağcaqanad öldürən lampa alış",
  "Kamera alış",
  "Alçipan alış",
  "Klips alış",
  "Hidroizolyator alış",
  "Perferator mikseri alış",
  "Germetik alış",
  "Metal kant alış",
  "Sviç kəlbətini alış",
  "Mebel ayağı alış",
  "Qapı amartizatoru alış",
  "Xətkeş",
  "Kapitel alış",
  "Ornament alış",
  "Plintus alış",
  "Stepler iynəsi alış",
  "Düymə alış",
  "Ayırıcı alış",
  "Lehim çubuğu alış",
  "Akkumulyator alış",
  "Ştepsel alış",
  "LED lent alış",
  "Elektrik dönüşdürücüsü alış",
  "Beylerbeyi göbek rakısı alış",
  "Mal içalatı alış",
  "Viski bakalı alış",
  "Parça alış",
  "Sap alış",
  "Düymə qəlibi alış",
  "İnşaat tərəzisi alış",
  "Qəlyan kolbası alış",
  "Kəfkir alış",
  "Mətbəx sürtkəci alış",
  "Kəlbətin alış",
  "Pizzakəsən alış",
  "Blender alış",
  "Sürmə çəkməcəsi alış",
  "Tərəcə dayağı alış",
  "Corona(0,355) alış",
  "Keçə alış",
  "Metrə alış",
  "Zəng düyməsi alış",
  "Kart oxuyucu alış",
  "RFID alış",
  "Multimetr alış",
  "Bunik alış",
  "Cem alış",
  "Şokolad yağı alış",
  "Qatlaşdırılmış süd alış",
  "Tost çörəyi alış",
  "Sucuq alış",
  "Mətbəx mebeli qapı çərçivəsi alış",
  "Balqabaq alış",
  "Kombi alış",
  "Ziqzaq(0,33) alış",
  "Amerikanka alış",
  "Qələm qəddiyən alış",
  "Yağ təmizləyən dərman alış",
  "Slivki alış",
  "Taati alış",
  "Vaniş alış",
  "Quru göyərti alış",
  "Pizza qutusu alış",
  "Paprika alış",
  "Ətotu alış",
  "Marker alış",
  "Sprite(2) alış",
  "Sprite(1,5) alış",
  "Soyuq kofe(0,24) alış",
  "Sibas alış",
  "Çili sous alış",
  "Tobasko alış",
  "Yaşıl çay alış",
  "Balsamik sous alış",
  "Kapers alış",
  "Ançous alış",
  "Zoğal əzməsi alış",
  "Marmelad alış",
  "Toyuq qanadı alış",
  "Sirop alış",
  "Qazlı su alış",
  "Nanə alış",
  "Qara paket çay alış",
  "Kəsmik alış",
  "Vanil alış",
  "Kasris Kasri alış",
  "Qazan alış",
  "Kürək alış",
  "Vençik alış",
  "Kartof əzən alış",
  "Cəm alış",
  "Qəlib alış",
  "Maşa alış",
  "Dizel alış",
  "Fanta(1) alış",
  "Kola(1) alış",
  "Qazsız su(0,5) alış",
  "Bulbaş alış",
  "Salat doğrayan alış",
  "Balıq unu alış",
  "Kakao alış",
  "Sprite(0,33) alış",
  "Oreo alış",
  "Duzlu çöp alış",
  "Zavod pendiri alış",
  "Qaynadılmış tərəvəz alış",
  "Qırmızı kələm turşusu alış",
  "Tbilisoba 7 year alış",
  "Tbilisoba 10 year alış",
  "David brandy alış",
  "Titsiani 3 year alış",
  "Titsiani 5 year alış",
  "Jack Daniels Honey alış",
  "Smirnoff alış",
  "Karva(0,5) alış",
  "Nataxtari gold(0,5) alış",
  "Stella Artois(0,33) alış",
  "Ev çaxırı alış",
  "A4 kağızı alış",
  "Zirə alış",
  "Təzyiq ölçən alış",
  "İlkin tibbi yardım dəsti alış",
  "Zəncəfil alış",
  "Dorado alış",
  "Qırmızı kürü alış",
  "Herkules alış",
  "Küncüt alış",
  "Yumşaldıcı alış",
  "Timsah açar alış",
  "Jelibon alış",
  "Jelatin alış",
  "Kreker alış",
  "Əlüzyuyan alış",
  "Pul rezini alış",
  "Gavalı qurusu alış",
  "Nişasta alış",
  "Hisəverilmiş asetrin alış",
  "Nugget alış",
  "Avtomobil yağı alış",
  "Qarğıdalı unu alış",
  "Balıq konservi alış",
  "Doşab alış",
  "Qulaq çöpü alış",
  "Qoğal alış",
  "Donuz alış",
  "Zandukeli alış",
  "Dekorativ qazon alış",
  "Qab yuma tabletkası alış",
  "Hil alış",
  "Menyü alış",
  "Avtomat qutusu alış",
  "Şampun alış",
  "Qapı kilidi alış",
  "Kabakçi alış",
  "Su nasosu alış",
  "Su tənzimləyici alış",
  "Plasmas qapaqcıq alış",
  "Plasmas borucuq alış",
  "Enerji yığdıran alış",
  "Hisəverilmiş balıq alış",
  "Hisəverilmiş skumbriya alış",
  "Hisəverilmiş şamayka alış",
  "Hisəverilmiş sazan alış",
  "Hisəverilmiş paltus alış",
  "Qazsız su(0,75) alış",
  "Generator alış",
  "Qazsız su(0,33) alış",
  "The Macallan 12 Years Fine Oak alış",
  "Dardimandi - Rkatsiteli alış",
  "Dardimandi - Alazani Valley white alış",
  "Svan duzu alış",
  "Fuqa alış",
  "Metlax klipsinin pazı alış",
  "İpəzor alış",
  "Oyuncaq alış",
  "Kokteyl çöpü alış",
  "Buz aparatı alış",
  "Budweiser(0,5) alış",
  "Red Bull(0,355) alış",
  "Qiymət kağızı aparatı alış",
  "Yuma yerinin pultu alış",
  "Yüksək təzyiq klapanı alış",
  "Alçaq təzyiq klapanı alış",
  "Solenoid ölçmə nasosu alış",
  "Stend alış",
  "Pantoqraf alış",
  "Yuma pistoletinin qını alış",
  "Pantoqrafa quraşdırılan fırlanan dirsək alış",
  "Birbaşa fırlanan dirsək alış",
  "Köpük vuran alış",
  "Köpük vuran lüləsi alış",
  "Yırğalanma yastığı alış",
  "Hidravlik şlank alış",
  "Çevirici alış",
  "Birbaşa fitinq alış",
  "Gilzə alış",
  "Əyri fitinq alış",
  "Köpük vuranın filtri alış",
  "Tas alış",
  "Su filtri alış",
  "Kömür kartrici alış",
  "Mavi kartric alış",
  "Rezervar alış",
  "Katyonit alış",
  "Rəqəmsal su yumşaltma cihazı alış",
  "Tərs filter alış",
  "Sediment kartric alış",
  "Karbon filtri alış",
  "Aktiv kömür kartrici alış",
  "Vorçester sousu alış",
  "Adapter alış",
  "Preslənmiş bordür alış",
  "Bar rezini alış",
  "Üfüqi karusel alış",
  "Yaylı oyuncaq gəmi alış",
  "Fırlanan konus alış",
  "Budweiser(0,33) alış",
  "Çətir alış",
  "Kondisioner alış",
  "Buxar ütüsü alış",
  "Fısdıq alış",
  "Karniz alış",
  "Çiləyən alış",
  "Kremlin alış",
  "Püstə alış",
  "Pambıq alış",
  "Laminant alış",
  "Agraf alış",
  "Drel burğusu alış",
  "Manometr alış",
  "Köpük örtüklü polistirol alış",
  "Trap alış",
  "Gigiyenik duş alış",
  "Xidmət alış",
  "Plasmas mufta alış",
  "Pizza sousu alış",
  "Bagrationi - Şampan alış",
  "LED səhnə işıqlandırması alış",
  "Toyuq budu alış",
  "Beton alış",
  "Rezin dənəcik alış",
  "Ülgüc alış",
  "Diş pastası alış",
  "Diş fırçası alış",
  "Vintaçan alış",
  "Elektrikli sürtgəc alış",
  "Bülöv alış",
  "Açar alış",
  "Armatur alış",
  "Chisti Rosi alış",
  "Spelta alış",
  "Mozarella alış",
  "Hennessy-XO alış",
  "Alüminium pəncərə alış",
  "Divar dekoru alış",
  "Çətir dayağı alış",
  "Burn(0,250) alış",
  "Pendir sousu alış",
  "Krevetlər alış",
  "OSB alış",
  "Quru süd alış",
  "Ayran alış",
  "Buz qabı alış",
  "Turniket alış",
  "Qəpik qəbul edən alış",
  "IPR düyməsi alış",
  "Sarajişvili-5 alış",
  "Soyuq çay(0,500) alış",
  "Günəbaxan tumu alış",
  "Dam örtüyü alış",
  "Şokolad tozu alış",
  "Likani(1) alış",
  "Tərəvəz soyan alış",
  "İstiridyə sousu alış",
  "Süni qranit piltə alış",
  "Plasmas stəkan alış",
  "Üz qırxan dəsti alış",
  "Siçan tutan yapışqan alış",
  "Vodka 111 alış",
  "Efes alış",
  "Enerji \"Max Power\" alış",
  "Lowenbrau alış"
];

// İkisi avtomatik birləşir (təkrar olmadan ümumi axtarış kataloqu yaranır)
window.CATALOG_DATA = Array.from(new Set([...window.PIECE_PRODUCTS, ...window.OTHER_PRODUCTS]));